[project]
name = "llm-fragments-dir"
version = "0.1.0"
description = "Load directory/git/GitHub contents as LLM file fragments (with file names)"
readme = "README.md"
authors = [{name = "Simon Willison"}, {name = "Joel Martin"}]
license = "Apache-2.0"
requires-python = ">=3.9"
dependencies = [
    "llm"
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project.urls]
Homepage = "https://github.com/kanaka/llm-fragments-dir"
Changelog = "https://github.com/kanaka/llm-fragments-dir/releases"
Issues = "https://github.com/kanaka/llm-fragments-dir/issues"
CI = "https://github.com/kanaka/llm-fragments-dir/actions"

[project.entry-points.llm]
fragments_dir = "llm_fragments_dir"

[project.optional-dependencies]
test = ["pytest"]
