[project]
name = "llm-fragments-git"
version = "0.1.0"
description = "Load directory/git/GitHub/Issue contents as LLM fragments"
readme = "README.md"
authors = [{name = "Simon Willison"}, {name = "Joel Martin"}]
license = "Apache-2.0"
requires-python = ">=3.9"
dependencies = [
    "llm"
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project.urls]
Homepage = "https://github.com/kanaka/llm-fragments-git"
Changelog = "https://github.com/kanaka/llm-fragments-git/releases"
Issues = "https://github.com/kanaka/llm-fragments-git/issues"
CI = "https://github.com/kanaka/llm-fragments-git/actions"

[project.entry-points.llm]
fragments_git = "llm_fragments_git"

[project.optional-dependencies]
test = ["pytest"]
