[project]
name = "llm-fragments-files"
version = "0.1.0"
description = "Load files (or whole directories/git repos) as fragments (with file names)"
readme = "README.md"
authors = [{name = "Simon Willison"}, {name = "Joel Martin"}]
license = "Apache-2.0"
requires-python = ">=3.9"
dependencies = [
    "llm"
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project.urls]
Homepage = "https://github.com/kanaka/llm-fragments-files"
Changelog = "https://github.com/kanaka/llm-fragments-files/releases"
Issues = "https://github.com/kanaka/llm-fragments-files/issues"
CI = "https://github.com/kanaka/llm-fragments-files/actions"

[project.entry-points.llm]
fragments_files = "llm_fragments_files"

[project.optional-dependencies]
test = ["pytest"]
